# Generated by Django 6.0.1 on 2026-01-16 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('monthly_amount', models.PositiveIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_uid', models.CharField(max_length=40, unique=True)),
                ('original_txn_id', models.CharField(blank=True, max_length=100)),
                ('txn_date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('kind', models.CharField(choices=[('REVIEW', 'Review'), ('UNMAPPED', 'Unmapped'), ('DUPLICATE', 'Duplicate')], max_length=10)),
                ('candidate_member_ids', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='core.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['month', 'kind', 'is_resolved'], name='core_except_month_075a6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount_due', models.PositiveIntegerField()),
                ('reference_code', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('REVIEW', 'Needs Review')], default='DUE', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='core.member')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_dues', to='core.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['month', 'status'], name='core_due_month_e35cea_idx'), models.Index(fields=['reference_code'], name='core_due_referen_5852ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('month', 'member'), name='uniq_due_month_member')],
            },
        ),
    ]
